### ISSUE TITLE
Slider Control

### ISSUE THREAD

**Issue by waynebaby** [Microsoft/MixedRealityDesignLabs_Unity#37]
do we have slider control like what we have in RS3 360 media player ?

**Comment by Railboy** [comment]
A generic slider control is in the works. We welcome requests and suggestions.

**Comment by waynebaby** [comment]
Thanks a lot

**Comment by waynebaby** [comment]
what's in my mind:

- A standard slider like what we have in 360 player support hor & Ver 
- a surrounding slider, bends like objectCollection
    - cos HoloLens and AR have different view angle, a degree parameter and a distance parameter would be helpful 
    - buttons like [<<][<][>][>>]  would be helpful cos the bending position is kinda tricky
