### ISSUE TITLE
The sounds of "Compound button sounds" don't work

### ISSUE THREAD

**Issue by alelay** [Microsoft/MixedRealityDesignLabs_Unity#49]
Hi (again) !

Since I passed to Unity 2017.1, none of the sounds work when I run the application on Hololens ... 
Bug ?

Thanks

**Comment by taylorjames9** [comment]
I'm looking at this now. When I play the SimpleDialogue_Example scene in the editor, and click a button, a new prefab called SimpleDialogShell is instantiated. It's this new dialog that has the "Close" button, and it's this close button that is missing a DefaultButtonSoundsProfile. A simple solution would be to re-add the button profile reference in the SimpleDialogShell prefab, but unfortunately, this object reference is consistently rejected for reasons that aren't immediately apparent. Until we commit a fix, I suggest avoiding the use of the SimpleDialogueShell prefab. Instead, create another prefab or duplicate the DialogAndMenuExample and adjust it until it what you need. You could avoid using prefabs by simply having other dialog boxes off, until it's they're time to turn on. 


![buttonsoundprofile](https://user-images.githubusercontent.com/3469247/29474058-eac9a0c0-840e-11e7-82cb-2f1a41b81590.PNG)

**Comment by taylorjames9** [comment]
Hi @alelay We're updating some of these features to work nicely with Unity 2017. We've just pushed a change to make the button profiles more stable. Please feel free to try them out now, and let us know if you're still getting log errors or missing sounds related to buttons.

**Comment by alelay** [comment]
Ok nice thanks !

**Comment by alelay** [comment]
I'm sorry but the buttons sound still mute on hololens build only (no problem when I test in the Unity editor) ... 
There is the same problem in the DesignLabs_Unity_Examples project too. :(

**Comment by Railboy** [comment]
Thanks for the update, we'll keep investigating.
