### ISSUE TITLE
MRDL Hololens Prefab still needs HoloToolkit Input Manger Prefab for OnInputClicked?

### ISSUE THREAD

**Issue by markleeyw** [Microsoft/MixedRealityDesignLabs_Unity#50]
MRDL has a the Hololens Prefab which allows interaction with MRDL elements without the need for HoloTookKit Input Manager Prefab.

However,  if I want to use the method public void OnInputClicked(InputClickedEventData on my GameObjects , I noticed I still have to add in HoloTookKit Input Manager Prefab.

Is there a way to only use MRDL's input management? Hope someone can help or clarify the best approach to use.

Thank you!

**Comment by paseb** [comment]
Hi @markleeyw, We're in the process of merging MRDL and HTK inputs to use the same input manager and input system.  That will remove the discrepancies.  See this issue thread: https://github.com/Microsoft/MRDesignLabs_Unity_Tools/issues/12

thanks,
-pat
