### ISSUE TITLE
Hand gesture scale too much?

### ISSUE THREAD

**Issue by fisher8096** [Microsoft/MixedRealityDesignLabs_Unity#55]
I was trying to move my project from Unity 5.6.1f1 to 2017.1.0f3.
So I make a fresh project and clone the lastest MRDesignLabs_Unity.
When I trying to manipulate the object in the example, this happended 

![_2017_09_01_18_03_43_373](https://user-images.githubusercontent.com/7721043/29965541-88fd5ac0-8f40-11e7-839d-c03e4ff43057.gif)

As I drag and move my hand a little bit, the interaction goes really off. 
Is this a bug or should I change some threshold value for dragging?

**Comment by Railboy** [comment]
The 2017 upgrade process hasn't been completed, so we're treating this as expected behavior until we're certain all input issues have been locked down.

Until then you adjust input scaling in the BoundingBoxShell prefab here:
![boundingboxscale](https://user-images.githubusercontent.com/9789716/30076334-5f64b286-922d-11e7-8992-393bc4753c17.PNG)

**Comment by fisher8096** [comment]
Thanks for the Info, looking forward to the future update.
Also, changing the input scale doesn't seems to solve the the problem, it just make it scale slower.
Once the manipulation is started, it seems like it iterate infinitely regardless my hand position until I release my hand.

**Comment by omrias** [comment]
Same problem here. Did anyone find a solution?

**Comment by ryryqtpi** [comment]
I'm experiencing the same issue running this in the editor using the remote connection for Hololens. Please look into this... I already downgraded to 2017.1, but it's not working at all.

**Comment by ryryqtpi** [comment]
Is the 2017 upgrade complete? Why has this issue been marked as resolved with no explanation as to a solution or further update?
