### ISSUE TITLE
need use holograms app cursor

### ISSUE THREAD

**Issue by kirabo** [Microsoft/MixedRealityDesignLabs_Unity#56]
holograms app cursor experience is very good, if there is a demo just fine
”App Bar and Bounding Box“ cursor experience is not very good

**Comment by Railboy** [comment]
Hi kirabo - could you elaborate? Is the cursor not behaving as expected?

**Comment by kirabo** [comment]
![test](https://user-images.githubusercontent.com/20675464/30354981-dbc52712-9862-11e7-8fc6-d4088efb5116.jpg)

**Comment by kirabo** [comment]
Can provide sample？please help
