### ISSUE TITLE
When will MRDL be merged with MRTK

### ISSUE THREAD

**Issue by hridpath** [Microsoft/MixedRealityDesignLabs_Unity#59]
Now that we are getting very close to the Windows Creators Edition  release and the Release of the MR Headsets, It would be nice to have the tools we use integrated and stableized for Unity 2017.2 that was just released. Would anyone be able to provide a timeframe for this integration?

Thanks, HR

**Comment by taylorjames9** [comment]
It's a little hard to say for certain, given the whirlwind leading up to the aforementioned product launch, but we hope to have a first-pass, usable version of the integrated MRTK within two weeks. @paseb may have a more accurate view of the timeline.

**Comment by paseb** [comment]
Hi @hridpath,

We'll be integrating some of the tools from MRDL into MRTK once the build and apis stabilize.  That will coincide with the public release of 2017.2 when it's out of beta.  I will have an updated fork this week for those that would like to preview or take a look at it integration and what functionally we're going to initially pull over.

thanks,
-pat

**Comment by cre8ivepark** [comment]
@hridpath This is the pull request for the initial migration of MRDL's fundamental elements
https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1007

**Comment by cre8ivepark** [comment]
First set of UI controls and building blocks are merged. 
https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1197

# This PR brings baseline functionality and UI controls from MRDL

Buttons(Interactable Object)
Interaction Receivers
Object Collection
Two test scenes were included under Assets/HoloToolkit-Examples/UX/Scenes. InteractableObjectExample.unity and ObjectCollectionExample.unity
# Next UI controls and utilities that we will bring from MRDL

App Bar and Bounding Box (with updated support for motion controllers)
Dialogs
Progress(loading indicator)
Hand coach(from Lunar Module)
Tool tips and Tool tip manager
Motion controller pointer visualizations (Straight & Parabolic)
Radial menu system
Debug Menu and Debug Panel
Solvers
Utility Extensions

Thanks!

**Comment by Druelik** [comment]
When do you think you will finish the merge completely. So the whole MRDL will be in MRTK?

**Comment by paseb** [comment]
Hi @Druelik 

I don't think we will ever have the whole of MRDL integrated into MRTK otherwise there wouldn't be a MRDL.  The simple reason is that we will always have functionality that will be seen as experimental and exploratory.  We're trying to migrate what is really core functionality that should be part of MRTK into MRTK.  As we migrate we will update MRDL with the correct version of MRTK and make sure everything plays nice.

thanks,
-pat
