### ISSUE TITLE
Disabling Bounding Box Target

### ISSUE THREAD

**Issue by HattMarris1** [Microsoft/MixedRealityDesignLabs_Unity#63]
When Bounding Box target is disabled, the Bounding box still moves around it, and the AppBar still appears.

What I'm looking to achieve is to have a "Lock" button, which disables the bounding box for a given object, so other controls on the object can be used.

**Comment by HattMarris1** [comment]
I'm assuming from the enhancement tag there's no way to do this currently?

**Comment by Railboy** [comment]
Correct, that's something you would currently have to add.

**Comment by Railboy** [comment]
Absolutely!

**Comment by Tanja-L** [comment]
Disabling bounding box target doesn't take any effect. It took me a few hours to figure out a solution to disable and enable the bounding box via script.
When the application is running the script creates a new Game Object called BoundingBoxShell(Clone) which has a BoundingBoxManipulate script that holds a target property. Find the BoundingBoxShell(Clone) and the BoundingBoxManipulate script component. Then set the target to null to disable the bounding box. To enable the box, assign the Transform of the GameObject that you want to scale and rotate to the target property of BoundingBoxManipulate.
I haven't tested it for multiple game objects and bounding boxes , but it works well if you only have one main object collection with a bounding box in your scene.

**Comment by HattMarris1** [comment]
Thanks for the response @Tanja-L, I might be misunderstanding you here, but surely the boundingbox just retargets the object as soon as you tap on it again?

What I'm looking to achieve is to allow the user to interact with ui elements on the object itself, and what I've found is that the boundingbox's collider is in the way.

**Comment by HattMarris1** [comment]
My solution to this was to create another boundingbox in which I could disable the collider

**Comment by Tanja-L** [comment]
You are right. I forgot to mention that I also disable the main collider around my object collection, so the bounding box doesn't reactivate itself and interaction with the child objects is possible.
