### ISSUE TITLE
ArgumentException: Invalid type: WorldGraphicsRaycaster+RayEventData

### ISSUE THREAD

**Issue by frimy** [Microsoft/MixedRealityDesignLabs_Unity#67]
Hello, I have that issue that raises in the editor when I play the program:

"ArgumentException: Invalid type: WorldGraphicsRaycaster+RayEventData passed to event expecting UnityEngine.EventSystems.AxisEventData
UnityEngine.EventSystems.ExecuteEvents.ValidateEventData[AxisEventData] (UnityEngine.EventSystems.BaseEventData data) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:14)
UnityEngine.EventSystems.ExecuteEvents.Execute (IMoveHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:120)
UnityEngine.EventSystems.ExecuteEvents.Execute[IMoveHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction1 functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261) UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction1)
HUX.Focus.FocusManager:ExecuteUIFocusEvent(GameObject, PointerEventData, EventFunction`1) (at Assets/MRDesignLab/HUX/Scripts/Focus/FocusManager.cs:222)
HUX.Interaction.InteractionManager:ManipulationUpdatedEvent(AFocuser, Vector3, Ray) (at Assets/MRDesignLab/HUX/Scripts/Interaction/InteractionManager.cs:764)
HUX.Interaction.InteractionManager:Update() (at Assets/MRDesignLab/HUX/Scripts/Interaction/InteractionManager.cs:167)"

It raises in Visual Studio when I remote on the Hololens and when I use UI elements such as scrolling too:
Exception thrown: 'System.ArgumentException' in UnityEngine.UI.dll
ArgumentException: Invalid type: WorldGraphicsRaycaster+RayEventData passed to event expecting UnityEngine.EventSystems.AxisEventData
   at UnityEngine.EventSystems.ExecuteEvents.ValidateEventData[T](BaseEventData data)
   at UnityEngine.EventSystems.ExecuteEvents.Execute(IMoveHandler handler, BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute[T](GameObject target, BaseEventData eventData, EventFunction`1 functor) 
(Filename: <Unknown> Line: 0)

I wrote on the Hololens forum and the mod told me to put the issue here.
Thank you in advance for resolving this,

Regards

**Comment by olifilo89** [comment]
Hi frimy, I got the same error and I still have the same issue. Hope someone could give us any hint.

I've seen the solution by https://forum.unity.com/threads/unity-ui-on-the-hololens.394629/ but I don't get how to solve the problem in my case.
I'm using HUX toolkit and Unity2017. 

Best

**Comment by frimy** [comment]
Hello olifilo89, I used the same solution and I have the same configuration. I hope it will be corrected soon, I am blocked with this error...
Have a nice day!

**Comment by taylorjames9** [comment]
Hey, the post that you're linking at was written in 2015. The unfortunate fact at the moment is that UnityUI and HoloLens, don't play nicely together. That's why HUX has it's own way of doing buttons, button collections, simple menus and dialog screens. Scroll down the ReadMe here to learn more about how menus and buttons works in HUX/MRDL:  [(https://github.com/Microsoft/MRDesignLabs_Unity)] Also a quick heads up, there is a merger happening between HUX/Holotoolkit that you can learn about here: [(https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1007)]

**Comment by frimy** [comment]
Hey, ty for your answer. I did everything there is in the readme of the MRDL, but there is a lack of content (which I understand as it is new). Unfortunately there are some stuff the MRDL does not and I need Holotoolkit and canvas too... that is why I am blocked at the moment and don't know what to do. The error makes the device to lag severely when I press a button, and if I use a scrollbar, the app will lag and hurt the eyes until we kill the app.

I hope the merge will come soon.
Regards

**Comment by frimy** [comment]
Good morning,

Do you have any news?
Thank you in advance.

**Comment by Railboy** [comment]
Hi @frimy - thanks for your patience. Hopefully we can help you get this sorted out.

To help you diagnose this we'll need some information about your setup. All these tools are in a state of flux so errors can result from mismatches between any combination of them:
- Which version of Unity you're using
- Which version of Visual Studio you're using
- Which version of the SDK you have installed
- Which branch of MRDL you're using (master or 2017.2-Dev)

**Comment by cre8ivepark** [comment]
Hi @frimy FYI, the first phase of MRDL to MRTK merge is done. You can find Interactable Object (button examples), Object Collection, Interaction Receiver and other useful building blocks in MRTK.

https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1197

You can find the example scene in MRTK:
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/UX/Readme/README_InteractableObjectExample.md
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/UX/Readme/README_ObjectCollection.md

## # UI controls and building blocks from MRDL to MRTK (Merge completed)
•	Buttons(Interactable Object)
•	Interaction Receivers
•	Object Collection
•	Line creation / Rendering classes for parabolic pointers
•	Multi-step pointer for parabolic pointers

## # Next UI controls and utilities that we will bring from MRDL
•	App Bar and Bounding Box (with updated support for motion controllers)
•	Dialogs
•	Progress(loading indicator)
•	Hand coach(from Lunar Module)
•	Tool tips and Tool tip manager
•	Motion controller pointer visualizations (Straight & Parabolic)
•	Radial menu system
•	Debug Menu and Debug Panel
•	Solvers
•	Utility Extensions

**Comment by frimy** [comment]
Hello Railboy,
I am using:
- Unity 2017.1.0f3
- Visual Studio Community 2015
- MRDesignLabs master
- Holotoolkit: I don't know where to find the version? It is from August, the 25th

**Comment by frimy** [comment]
cre8ivepark It looks great! I am going to dowload it now. Thank you.
