### ISSUE TITLE
Building UWP App in Unity Continuously Fails

### ISSUE THREAD

**Issue by mitchlotierzo** [Microsoft/MixedRealityDesignLabs_Unity#71]
I'm aware this may not directly be an issue with the HoloLens and MRDesignLabs tools, but I'm asking it regardless because I am going insane here. Literally, nine times out of ten when I go to build a UWP app, it fails with the error message below:

"
IOException: Failed to move Temp\StagingArea\Data\Managed\Plugins to Temp\StagingArea\Plugins.: Access is denied.

Utility.ThrowWin32IOException (Int32 errorCode, System.String message) (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/Utility.cs:353)
Utility.MoveDirectory (System.String source, System.String destination, System.Func`2 shouldOverwriteFile) (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/Utility.cs:462)
Utility+<MoveDirectorySlowPath>c__AnonStorey2.<>m__0 (System.String fileName, FileAttributes fileAttributes) (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/Utility.cs:484)
Utility.EnumerateDirectoryRecursive (System.String path, System.Func`3 onFileEnumerated) (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/Utility.cs:580)
Utility.MoveDirectorySlowPath (System.String source, System.String destination, System.Func`2 shouldOverwriteFile) (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/Utility.cs:477)
Utility.MoveDirectory (System.String source, System.String destination, System.Func`2 shouldOverwriteFile) (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/Utility.cs:469)
PostProcessWinRT.MoveDataManagedToRoot () (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:527)
PostProcessWinRT.Process () (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:152)
UnityEditor.WSA.BuildPostprocessor.DoPostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:155)
UnityEditor.WSA.BuildPostprocessor.PostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:162)
UnityEditor.HostView:OnGUI()
"

It seems to happen randomly too. I have tried:
- Disabling any anti-virus software scans on the development machine.
- Restarting Unity.
- Deleting the old build folder before attempting to rebuild again.
- Disabling Windows Indexing Services on my Unity project folder.
- Changing the UAP version in my "project.lock.json" file to just "10.0".

I'm not sure what else to try. It's getting infuriating.

ANY HELP would be greatly appreciated!

**Comment by paseb** [comment]
Hi @mitchlotierzo,

Which version of Unity are you using?  Also which plugins are you using and is this straight out of the DesignLabs project or your own project?  This is a file IO write error in the pre-build step setting up kicking out he UWP solution and project.  

I would look for anything that would use or have a lock on any dlls you have in the project.  One thing I ran into in the past but only on the VS build side was having telemetry locking files in the solution:

- Help -> Send Feedback -> Settings
- Uncheck the box opting you into the customer experience improvement program.

Try that and see if it resolves it.  

thanks,
-pat

**Comment by mitchlotierzo** [comment]
I am using the latest release of Unity 2017.1. I recreated the BoundingBox example scene.

**Comment by mitchlotierzo** [comment]
This seems to happen before the previously mentioned error too:

"
UnityEditor.BuildPlayerWindow+BuildMethodException: Build failed with errors.
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x001b9] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:162 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00050] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:83 
UnityEditor.HostView:OnGUI()
"

**Comment by mitchlotierzo** [comment]
So, I just deleted my Library folder and recompiled everything, then restarted, then tried to build again and it seemed to work. This is crazy.

**Comment by mitchlotierzo** [comment]
I have a suspicion that one of the plugins could be causing a conflict. I'm not entirely sure.

**Comment by mitchlotierzo** [comment]
Okay. It seems to be something with the Vuforia plugins.

**Comment by SimonRPI** [comment]
I have the same issue. But I had this problem also before I used Vuforia.
I hvae to close all VS Projects to build the project
Sometimes it is working with open VS

**Comment by tommensink** [comment]
Same issue for a few months now. Only with the higher versions of Unity and not using Vuforia in the current project, using Unity 2018.2.2f1. Sometimes deleting the temp folder works, other times just trying a number of time. Is really not nice, often working with 2017.1 just for avoiding this and similar issues.

**Comment by krishnanpc** [comment]
Had the same error, just had a deployment running in background (visual studio!)

**Comment by tallchristos** [comment]
> So, I just deleted my Library folder and recompiled everything, then restarted, then tried to build again and it seemed to work. This is crazy.
This solution worked for me (Unity 2020). Thank you very much mitchlotierzo .
