### ISSUE TITLE
Poor performance?

### ISSUE THREAD

**Issue by MartinVoehringer** [Microsoft/MixedRealityDesignLabs_Unity#76]
First off, apologies if this is not the right place to ask such a question. I really like the samples and i realize that this repo is called "Labs" for a reason, but I'm starting to wonder if I am doing something wrong when deploying the provided examples. In near all of them I get 30 fps max. 

Examples are:
* Lunar lander
* Button controls example

Things I've made sure:
* Deployed in release configuration
* HoloLens is up to date
* Not using mixed reality capture
* Using Unity 2017.1

When evaluating, I noticed such a drop even with only one button in the scene and nothing else. No light components at all. Is this normal or am I missing something (I noticed in other projects that the performance is quick to drop to 30 fps but rarely goes below that, that's why I got suspicious).
Thanks in advance for any insight.

**Comment by cre8ivepark** [comment]
@Railboy Any insights on this?

**Comment by Railboy** [comment]
That's definitely not normal. One button shouldn't affect performance. If I had to guess I'd say it sounds like something is spamming the log with messages / warnings / errors. You might try dropping our Debug prefab into your project to see if that's the case. It can be found in Assets/MRDesignLab/HUX/Prefabs/Debug
