### ISSUE TITLE
Interact with the bounding box in the unity editor?

### ISSUE THREAD

**Issue by fabioshepherd** [Microsoft/MixedRealityDesignLabs_Unity#82]
Hi! Could I interact with the bounding box directly in the unity editor for doing tests? The AppBar and the bounding box appear after I click on the object, but after I can't do any manipulation using the bouding box.

**Comment by Tachoron** [comment]
Same by me.

I suppose this will not work inside the editor.
You must use the Emulator or the Device for testing this.

Best Regards
Tachoron

**Comment by Zulex** [comment]
The bounding box interaction doesn't work on the Unity editor but only on the HoloLens, this behaviour is expected.

Could you get the bounding box to work on the HoloLens? When I click on a object inside the unity editor the bounding box appears, but this doesn't work on the HoloLens. Im using the 2017.2 branch.

**Comment by Tachoron** [comment]
I using the 2017.1 release at the moment and it works (= i can manipulate the object).
I will update to 2017.2 soon and add new informations if my HoloLens is fixed (hardware problems).

**Comment by Zulex** [comment]
Downgrading to unity 2017.1 fixed the problem for me:)

**Comment by filsv** [comment]
@Zulex the same for me, but if I click with a mouse it's work. (not with air-tap). and after this drag works with hand-gesture.
