### ISSUE TITLE
AppBar/Toolbar Captions and Single Pass Stereo Rendering 

### ISSUE THREAD

**Issue by Tachoron** [Microsoft/MixedRealityDesignLabs_Unity#85]
Not sure if this is too special, but if i have enabled **Single Pass Stereo Rendering** to optimize the Performance i have checked that the **AppBar/Toolbar Labels** are only visible for one eye therefore very difficult and unpleasant to read (flickering effect).

**Best Regards and big praise to your great project!**
Tachoron

**Comment by paseb** [comment]
Yep, those are older shaders that were never updated for single pass instance rendering.  I'll look at patching them shortly.

thanks,
-pat
