### ISSUE TITLE
SolverRadialView should include an option for min / max x axis clamps

### ISSUE THREAD

**Issue by Railboy** [Microsoft/MixedRealityDesignLabs_Unity#9]
Since we frequently use SolverRadialView for billboarded menus we should include an option to clamp the x axis. Currently if the player is looking at the ceiling or floor when a SolverRadialView is enabled it can place menus in strange-looking positions - an x angle clamp would give devs a simple way to prevent this without the additional restrictions that come with SolverRectView.

**Comment by paseb** [comment]
@Railboy can you describe a bit more what you're seeing?  I can add a gravity aligned if you'd like which would make it not do vertical orientations.

**Comment by paseb** [comment]
Updated sync and let me know if you have any issues.  Here are the specifics:
`		public enum ReferenceDirectionEnum
		{
            /// <summary>
            /// Orient towards head including roll, pitch and yaw
            /// </summary>
			HeadOriented,
            /// <summary>
            /// Orient toward head but ignore roll
            /// </summary>
			HeadFacingWorldUp,
            /// <summary>
            /// Orient torwards the head movement direction found in veil singleton
            /// </summary>
			HeadMoveDirection,
            /// <summary>
            /// Orient towards head but remain vertical or gravity aligned
            /// </summary>
            HeadGravityAligned
		}`

**Comment by Railboy** [comment]
That should work - will test today.

**Comment by Railboy** [comment]
This is a useful addition but not what we were aiming for.

Here's an image to clarify::

![clampedrotation](https://user-images.githubusercontent.com/9789716/27511881-771f89c8-58e4-11e7-860a-1ee861526c5b.png)

**Comment by paseb** [comment]
Now I understand more what you're looking at but need to think of a better way of doing it.  The solver system is setup to have multiple solvers that can work independently on an object.  This would allow for a radial view solver with a height or pitch limiter.  I would hate to overload the radial view solver with a number of special case elements.  I'll look into it a bit more and propose something or find a more elegant way of adding it.

**Comment by Railboy** [comment]
Had a thought about this today - what about a constraint system similar to the solvers? Ie, multiple constraint components that are gathered and executed after the solvers.

**Comment by paseb** [comment]
You actually don't need anything in addition to solvers you just need a constraint solver :).  As in we can just add a constraint solver to the mix and it will work.  I'll do a quick first pass for you tomorrow and get a solver that works as a constraint solver.
