### ISSUE TITLE
SimpleDialog clarification

### ISSUE THREAD

**Issue by sGambolati** [Microsoft/MixedRealityDesignLabs_Unity#91]
Hi, guys!

I'm going crazy trying to implement a simple dialog with a Yes/No buttons. I'm trying to use the MRTK 2017.2 (same Unity Version).

What I got so far is that I could display the dialog but the buttons don't trigger the close event. 
I used as reference the SimpleDialog_Example scene but noted that there a crazy number of components and I don't understand anyone. 

BTW, the scene sample works and if I copy the scene structure, my scene works. But I don't understand what I missing to create a scene from scratch.

Thanks in advance.
SG.

**Comment by cre8ivepark** [comment]
@sGambolati Hi, currently in progress of bringing Dialog and Progress controls to MRTK. I'll post the link to the pull request this week.

**Comment by sGambolati** [comment]
Thanks!

**Comment by cre8ivepark** [comment]
@sGambolati Please check out the Pull Requests on MRTK 
https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1718
https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1783
