### ISSUE TITLE
AppBar always renders -2.9 m behind the hololens

### ISSUE THREAD

**Issue by mhoward2467** [Microsoft/MixedRealityDesignLabs_Unity#92]
I have a prefab that I instantiate via code, the prefab has the following scripts, a Compound Button, Bounding Box Target with a Box Collider.  Everytime time it renders, the app bar is always behind me. 

In the Unity I can see it and when I try to move it forward via the inspector it snaps back to its position.

Ive been stuck on this for weeks of and on, any help would be appreciated.

Env: Win10, Unity 2017.1.0p5

Thanks in advance

**Comment by paseb** [comment]
Hi @mhoward2467,

Can you provide code sample for how you're instantiating the prefab?  This is most likely and initialization issue with app bar post spawn.

thanks,
-pat

**Comment by mhoward2467** [comment]
@paseb Hello, here's the code and below is the actual values after the scaleClonePrefab get instantiated:

ScaleClonePrefab = Instantiate(UIContaindScaleClonePrefab, new Vector3(selectedUIContainerScript.transform.position.x,
                                            selectedUIContainerScript.transform.position.y, selectedUIContainerScript.transform.position.z),
                                            Quaternion.LookRotation(cameraForward, Vector3.up)); 
![image](https://user-images.githubusercontent.com/2371660/36338384-62e36748-1362-11e8-9c60-f2a7f6ee1929.png)

Thanks for taking time to look into this...
And here's the BoundingBoxShell settings
![image](https://user-images.githubusercontent.com/2371660/36338389-7f1911ec-1362-11e8-9e32-7e0cd4de8c6e.png)

**Comment by cre8ivepark** [comment]
@mhoward2467 Hi, we have ported Bounding Box and App Bar to MRTK. It works with the latest MRTK Dev_Working_Branch. Please check this pull request:
Microsoft/MixedRealityToolkit-Unity#1785

**Comment by mhoward2467** [comment]
Ok that's awesome, I will work n that this evening and let you know how it goes.

Thanks

Sent from my Windows 10 phone

________________________________

**Comment by mhoward2467** [comment]
Do you have a sample of attaching a bounding box and app bar to a newly instantiated object via code?

Sent from my Windows 10 phone

________________________________
