### ISSUE TITLE
Disable the remove button from the toolbar for manipulatble objects

### ISSUE THREAD

**Issue by bepierre** [Microsoft/MixedRealityDesignLabs_Unity#95]
Hey!

I love what you did here. I have a small issue: I have a game object with a collider, compound button and bounding box target and everythings is working well. However I would like to remove the Remove button from the toolbar that is displayed when I tap the object (or change the layer of that object instead of completely removing it).

I couldn't find the script where the script that receives the button interactions. 

Any help would be awesome!

EDIT: it looks like I could change AppBar.cs for this particular project. Is there a better solution?
EDIT2: I now changed UseRemove to false in AppBar.cs. It works but now manipulatable objects can never be removed. Do you have a better way?

**Comment by cre8ivepark** [comment]
@steuhh Hi, Thanks for the feedback! We recently ported Bounding Box and App Bar to MRTK(MixedRealityToolkit) which now has better shader and interaction behavior. Please check it out:
[https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit-Examples/UX/Readme/README_BoundingBoxGizmoExample.md](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit-Examples/UX/Readme/README_BoundingBoxGizmoExample.md)

**Comment by steuhh** [comment]
NIce! Thanks :)
