### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object HUX.Focus.FocusManager.ContainsValidFilter 

### ISSUE THREAD

**Issue by einstyle** [Microsoft/MixedRealityDesignLabs_Unity#97]
I added Compound Button and Bounding Box Target to a virtual character, but when I click on it I get this error:

NullReferenceException: Object reference not set to an instance of an object
HUX.Focus.FocusManager.ContainsValidFilter (UnityEngine.Transform transform) (at Assets/MRDesignLab/HUX/Scripts/Focus/FocusManager.cs:211)

What does it mean?
How to solve this?

**Comment by radicalad** [comment]
@einstyle we've sunset the HUX library to more fully support MRTK.
